name: Ping URL
description: Ping url until maximum triel

inputs:
  url: 
    description: url to ping
    required: true
  max_trials:
    description: maximum trials
    default: 10
    required: false
  delay: 
    description: delay in sec
    default: 5
    required: false

runs:
  using: docker
  image: Dockerfile