name: 03-Workflow Runners
on:
    workflow_dispatch:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latesh
        steps:
            - name: Show OS
              run: |
                echo "This job is running on an Ubuntu runner."
                echo "Runner OS: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash # without this windows will not echo
              run: |
                echo "This job is running on an Windows runner."
                echo "Runner OS: $RUNNER_OS"
    mac-echo:
        runs-on: mac-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on an MAC runner."
                echo "Runner OS: $RUNNER_OS"
