name: 08 - Variables
on:
    push:
    workflow_dispatch:
env:
    WORKFLOW_VAR: "I am a workflow var"
jobs:
    echo:
        runs-on: ubuntu-latesh
        env:
            JOB_VAR: "I am job env var"
        steps:
            - name: Print Env Variables
              env: 
                STEP_VAR: "I am a step env var"
                step-var2: "I am another step env var"
              run: |
                echo "Step env var: ${{env.STEP_VAR}}"
                echo "Step env var 2: $step_var2"
                echo "Job env var: ${{env.JOB_VAR}}"
                echo "Job workflow var: ${{env.WORKFLOW_VAR}}"