name: 18 - 3 - Reusable Workflow

on: 
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflow.yaml
        with:
            target-directory: dummy-dir
    e2e-tests:
        # uses: <owner>/<repo>/.github/workflows/<workflow_name>@<version>
        uses: pritesRane/github-actions-course-example-e2e/e2e.yaml@main